### ISSUE TITLE
Validação em nome de habilidades na hora da criação

### ISSUE THREAD

**Issue by JosielSantos** [ed2martin/intmud#3]
Não sei se esse é um bug no programa de exemplo "mud" ou no próprio código do intmud, mas poderia ter uma validação nos nomes das habilidades, informando que o nome é inválido quando assim o for.
Hoje ele informa que a a habilidade foi criada mas quando vamos editar ou listar ela não está lá.
Ex.: 
chab Caminho da alquimia - Preparar poções curativas

Obrigado!

**Comment by ed2martin** [comment]
O comando chab (e diversos outros, como cmag, cef, csocial, etc.) estava com problema de validação. Deveria dizer que esse nome não é permitido, tanto pelo hífen quanto pela quantidade de caracteres.
Acabo de fazer a correção.
